
#pragma once
enum  BODY_TYPE { STATIC_BODY, DYNAMIC_BODY, CHARACTER, PLATFORM, FLOOR, ROOF, RIGHT_WALL, LEFT_WALL, FOOT_SENSOR};
enum  DIRECCION { ESTATICO, IZQUIERDA, DERECHA, ARRIBA, ARRIBA_IZQUIERDA, ARRIBA_DERECHA};
//enum  WALL_TYPE { VERTICAL, HORIZONTAL};